paper: mccabe-1976-complexity
style: bracket
entries:
    - key: "1"
      raw: 'C. Berge, Graphs and Hypergraphs. Amsterdam, The Netherlands: North-Holland, 1973.'
      authors:
        - C. Berge
        - Graphs
        - Hypergraphs
      title: 'Amsterdam, The Netherlands: North-Holland, 1973'
      year: 1973
      resolves_to: ""
    - key: "2"
      raw: 'B. W. Boehm, "Software and its impact: A quantitative assessment," Datamation, vol. 19, pp. 48-59, May 1973.'
      authors:
        - B. W. Boehm
      title: 'Software and its impact: A quantitative assessment'
      venue: Datamation, vol. 19, pp. 48-59
      year: 1973
      pages: 48-59
      resolves_to: ""
    - key: "3"
      raw: W. B. Cammack and H. J. Rogers, "Improving the programming process," IBM Tech. Rep. TR 00.2483, Oct. 1973.
      authors:
        - W. B. Cammack
        - H. J. Rogers
      title: Improving the programming process
      venue: IBM Tech. Rep. TR 00.2483, Oct
      year: 1973
      resolves_to: ""
    - key: "4"
      raw: D. E. Knuth, "Structured programming with GOTO statements," Computing Surveys, vol. 6, pp. 261-301, Dec. 1974.
      authors:
        - D. E. Knuth
      title: Structured programming with GOTO statements
      venue: Computing Surveys, vol. 6, pp. 261-301, Dec
      year: 1974
      pages: 261-301
      resolves_to: ""
    - key: "5"
      raw: R. Kosaraju, "Analysis of structured programs," J. Comput. Syst. Sci., vol. 9, pp. 232-255, Dec. 1974; also, Dep. Elec. Eng., The Johns Hopkins Univ., Baltimore, MD, Tech. Rep. 72-11, 1972.
      authors:
        - R. Kosaraju
      title: Analysis of structured programs
      venue: J. Comput. Syst. Sci., vol. 9, pp. 232-255, Dec. 1974; also, Dep. Elec. Eng., The Johns Hopkins Univ., Baltimore, MD, Tech. Rep. 72-11
      year: 1972
      pages: 232-255
      resolves_to: ""
    - key: "6"
      raw: H. Legard and M. Marcotty, "A generalogy of control structures," Commun. Assoc. Comput. Mach., vol. 18, pp. 629-639, Nov. 1975.
      authors:
        - H. Legard
        - M. Marcotty
      title: A generalogy of control structures
      venue: Commun. Assoc. Comput. Mach., vol. 18, pp. 629-639, Nov
      year: 1975
      pages: 629-639
      resolves_to: ""
    - key: "7"
      raw: H. D. Mills, "Mathematical foundations for structured programming," Federal System Division, IBM Corp., Gaithersburg, MD, FSC 72-6012, 1972.
      authors:
        - H. D. Mills
      title: Mathematical foundations for structured programming
      venue: Federal System Division, IBM Corp., Gaithersburg, MD, FSC 72-6012
      year: 1972
      resolves_to: ""
